spring.application.name=social-movie-club

# Veritabani Baglanti Ayarlari
spring.datasource.url=jdbc:postgresql://localhost:5432/social_movie_app
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (Tablo olusturma stratejisi)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# TMDB API Configuration
tmdb.api.key=a280a0afc357c389acebabd006351b42
tmdb.api.base-url=https://api.themoviedb.org/3


# JWT Ayarlar\u0131
socialmovieclub.app.jwtSecret=BuCokGizliVeUzunBirSifreOlmaliEnAz256BitKarakterTavsiyeEdilir
socialmovieclub.app.jwtExpirationMs=86400000
